syntax = "proto3";

option java_package = "com.playtab.cloudgateservice.grpc";
option java_multiple_files = true;

package cloudgate;

service OccupancyService {
  rpc GetOccupancy(StageRequest) returns (OccupancyResponse);
  rpc GetAllOccupancy(Empty) returns (AllOccupancyResponse);
  rpc StreamOccupancy(StageRequest) returns (stream OccupancyResponse);
}

message Empty {}

message StageRequest {
  int64 stage_id = 1;
}

message OccupancyResponse {
  int64 stage_id = 1;
  string stage_name = 2;
  int64 current_count = 3;
  int32 max_capacity = 4;
}

message AllOccupancyResponse {
  repeated OccupancyResponse occupancies = 1;
}
